// SPDX-License-Identifier: GPL-2.0-only
/*
 * nmi.c — NMI-exiting handler for phantom.ko
 *
 * With NMI exiting enabled (pin-based control bit 3), any NMI that
 * arrives while the guest is running causes a VM exit rather than
 * being delivered to the guest.
 *
 * On bare metal (Phase 2+):
 *   The NMI is real (watchdog, perf PMI, MCE, etc.) and must be
 *   re-delivered to the host kernel.  We use the APIC self-NMI
 *   technique (write NMI_VECTOR to ICR with SELF shorthand) — the
 *   same approach used by KVM's self_nmi().  The NMI fires into the
 *   host IDT after local_irq_enable() following the VM exit.
 *
 *   Without re-delivery, the hard lockup detector (perf PMU NMI at
 *   ~100 Hz checking hrtimer tick count) never sees its NMIs and
 *   concludes the CPU is locked up after 2 × watchdog_thresh seconds.
 *   With 4+ cores in VMX, enough watchdogs fire simultaneously to
 *   trigger a hard reset / panic.
 *
 * Under nested KVM (Phase 0–1):
 *   The "NMI VM exit" is generated by L0 KVM forwarding an NMI
 *   notification to L1.  The real NMI was already handled by L0.
 *   Re-delivering via APIC ICR in L1 causes L0 to forward it back
 *   as another NMI VM exit — infinite loop.  So under nested KVM we
 *   consume the NMI silently.
 *
 * Detection: boot_cpu_has(X86_FEATURE_HYPERVISOR) — set by CPUID
 * leaf 1 ECX[31] when running under any hypervisor (KVM, VMware,
 * Hyper-V, etc.).  Clear on bare metal.
 *
 * NMI-safe: no spinlocks, no non-reentrant structures, no sleeping.
 */

#include <linux/types.h>
#include <linux/cpufeature.h>
#include <asm/msr.h>
#include <asm/apic.h>
#include <asm/irq_vectors.h>

#include "nmi.h"

/**
 * phantom_handle_nmi_exit - Handle an NMI captured during guest execution.
 *
 * Called when exit reason VMX_EXIT_EXCEPTION_NMI (0) and interruption-info
 * shows vector=2 (NMI) with valid bit set.
 *
 * On bare metal: re-delivers the NMI to the host via APIC self-NMI so
 * that the host NMI handler (watchdog, perf, MCE) runs after VM exit.
 *
 * Under nested KVM: consumes the NMI silently (already handled by L0).
 */
void phantom_handle_nmi_exit(void)
{
	if (boot_cpu_has(X86_FEATURE_HYPERVISOR)) {
		/*
		 * Nested KVM: L0 already handled the real NMI.
		 * Self-NMI here would cause an infinite NMI loop.
		 */
		return;
	}

	/*
	 * Bare metal: re-deliver the NMI to the host kernel.
	 *
	 * The APIC self-NMI write queues an NMI at the local APIC.
	 * It will be delivered after the VM exit path calls
	 * local_irq_enable() — NMI delivery is blocked during the
	 * VM exit handler (CPU sets "blocking by NMI" on NMI exit),
	 * but the self-NMI via ICR posts a new NMI that will fire
	 * once the IRET from the current NMI context unblocks NMIs.
	 *
	 * This matches KVM's self_nmi() approach.
	 */
	__apic_send_IPI_self(NMI_VECTOR);
}
