// SPDX-License-Identifier: GPL-2.0-only
/*
 * nmi.c — NMI-exiting handler for phantom.ko
 *
 * With NMI exiting enabled (pin-based control bit 3), any NMI that
 * arrives while the guest is running causes a VM exit rather than
 * being delivered to the guest.
 *
 * Nested KVM note:
 *   In a nested-virtualisation environment (L0=KVM, L1=phantom, L2=guest),
 *   the "NMI VM exit" is generated by L0 KVM forwarding an NMI notification
 *   to L1.  The real hardware NMI has already been processed by L0 at the
 *   bare-metal level.  Attempting to re-deliver via APIC ICR from VMX-root
 *   mode in L1 causes L0 to process another synthetic NMI, which in turn
 *   gets forwarded back to L1 as another NMI VM exit — creating an infinite
 *   loop that permanently blocks the guest CPU.
 *
 * Correct behaviour:
 *   Simply consume the NMI VM exit and resume the guest.  The actual NMI
 *   (machine-check, perf counter, watchdog, etc.) was already serviced by
 *   L0 before it was forwarded to us as a VM exit event.
 *
 *   For bare-metal deployment (Phase 2+), proper NMI re-delivery uses the
 *   "virtual NMIs" pin control (PIN_BASED_VIRTUAL_NMIS) combined with
 *   NMI-window exiting (CPU_BASED_NMI_WINDOW_EXITING) to re-inject the
 *   NMI to the host via VMCS entry-interrupt-info once the NMI blocking
 *   window ends.  This is the approach used by KVM itself.
 *
 * NMI-safe: no spinlocks, no non-reentrant structures, no sleeping.
 */

#include <linux/types.h>
#include <asm/msr.h>

#include "nmi.h"

/**
 * phantom_handle_nmi_exit - Consume an NMI captured during guest execution.
 *
 * Called when exit reason VMX_EXIT_EXCEPTION_NMI (0) and interruption-info
 * shows vector=2 (NMI) with valid bit set.
 *
 * In the nested-KVM environment used for Phase 0–1 testing, the NMI was
 * already handled by the L0 hypervisor before being forwarded to L1
 * (phantom) as a VM exit.  We consume it silently and return so the guest
 * can be resumed.
 *
 * The caller (phantom_vm_exit_dispatch) returns 0 after this call, causing
 * the run loop to VMRESUME the guest immediately.
 */
void phantom_handle_nmi_exit(void)
{
	/*
	 * Nothing to do.  The NMI was already handled at the hardware level
	 * by L0 KVM.  Attempting APIC ICR self-NMI from VMX-root mode in a
	 * KVM guest causes the synthetic NMI to be forwarded back to us as
	 * another NMI VM exit — an infinite loop.
	 *
	 * For bare-metal deployment this function will be extended with the
	 * NMI-window exiting mechanism described in the file comment above.
	 */
}
